CLASS_COLORS = {
	WARRIOR = "|cffC79C6E",
	PALADIN = "|cffF58CBA",
	HUNTER = "|cffABD473",
	ROGUE = "|cffFFF569",
	PRIEST = "|cffFFFFFF",
	SHAMAN = "|cff0070DE",
	MAGE = "|cff69CCF0",
	WARLOCK = "|cff9482C9",
	DRUID = "|cffFF7D0A"
}

TW_CLASS_TOKEN = {
	enUS = {
		["Warrior"] = "WARRIOR",
		["Paladin"] = "PALADIN",
		["Hunter"] = "HUNTER",
		["Rogue"] = "ROGUE",
		["Priest"] = "PRIEST",
		["Shaman"] = "SHAMAN",
		["Mage"] = "MAGE",
		["Warlock"] = "WARLOCK",
		["Druid"] = "DRUID",
	},
	deDE = {
		["Krieger"] = "WARRIOR",
		["Paladin"] = "PALADIN",
		["Jäger"] = "HUNTER",
		["Schurke"] = "ROGUE",
		["Priester"] = "PRIEST",
		["Schamane"] = "SHAMAN",
		["Magier"] = "MAGE",
		["Hexenmeister"] = "WARLOCK",
		["Druide"] = "DRUID",
	},
	zhCN = {
		["战士"] = "WARRIOR",
		["圣骑士"] = "PALADIN",
		["猎人"] = "HUNTER",
		["盗贼"] = "ROGUE",
		["牧师"] = "PRIEST",
		["萨满祭司"] = "SHAMAN",
		["法师"] = "MAGE",
		["术士"] = "WARLOCK",
		["德鲁伊"] = "DRUID",
	},
	ruRU = {
		["Воин"] = "WARRIOR",
		["Паладин"] = "PALADIN",
		["Охотник"] = "HUNTER",
		["Разбойник"] = "ROGUE",
		["Жрец"] = "PRIEST",
		["Шаман"] = "SHAMAN",
		["Маг"] = "MAGE",
		["Чернокнижник"] = "WARLOCK",
		["Друид"] = "DRUID",
	},
	esES = {
		["Guerrero"] = "WARRIOR",
		["Paladín"] = "PALADIN",
		["Cazador"] = "HUNTER",
		["Pícaro"] = "ROGUE",
		["Sacerdote"] = "PRIEST",
		["Chamán"] = "SHAMAN",
		["Mago"] = "MAGE",
		["Brujo"] = "WARLOCK",
		["Druida"] = "DRUID",
	},
	ptBR = {
		["Guerreiro"] = "WARRIOR",
		["Paladino"] = "PALADIN",
		["Caçador"] = "HUNTER",
		["Ladino"] = "ROGUE",
		["Sarcedote"] = "PRIEST",
		["Xamã"] = "SHAMAN",
		["Mago"] = "MAGE",
		["Bruxo"] = "WARLOCK",
		["Druída"] = "DRUID",
	},
}
